config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :myquestions, only: [:index, :new, :create, :destroy] 
  root to: 'questions#top'
  resources :questions, only: [:index, :new, :create] do
    collection do
      get 'top'
      get 'quiz'
      get 'about'
    end
  end
  resources :users, only: :show 
  resources :pins, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/myquestion.rb
class Myquestion < ApplicationRecord
  validates :content, presence: true
  belongs_to :user
end

app/models/pin.rb
class Pin < ApplicationRecord
  belongs_to :user
  belongs_to :question
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :pins, foreign_key: 'question_id', dependent: :destroy
  has_many :users, through: :pins


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :myquestions, dependent: :destroy
  has_many :pins, dependent: :destroy
  has_many :questions, through: :pins

  def like(question)
    @pins = pins.find_or_create_by(question_id: question.id)
  end

  def unlike(question)
    pin = pins.find_by(question_id: question.id)
    pin.destroy if pin
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  def after_sign_in_path_for(resource)
    user_path(current_user)
  end
  
  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end


end

app/controllers/myquestions_controller.rb
class MyquestionsController < ApplicationController
  def index
    @myquestions = Myquestion.all
  end

  def new
    @myquestion = Myquestion.new
  end

  def create
    Myquestion.create(myquestion_params)
    redirect_to user_path(current_user)
  end

  def destroy
    myquestion = Myquestion.find(params[:id])
    myquestion.destroy
    redirect_to user_path(current_user)
  end

  private
  def myquestion_params
    params.require(:myquestion).permit(:content).merge(user_id: current_user.id)
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  def create
    question = Question.find(params[:question_id])
    current_user.like(question)
    redirect_to user_path(current_user)
  end

  def destroy
    question = Question.find(params[:question_id])
    current_user.unlike(question)
    redirect_to user_path(current_user)
  end


end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @questions = Question.all.page(params[:page]).per(7)
  end

  def new
    @question = Question.new
  end

  def create
    Question.create(question_params)
  end

  def top

  end

  def about

  end

  def quiz    
    question = Question.all
    @quiz = question.sample
  end

end

app/controllers/quiz_controller.rb
class QuizController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
    @user = User.find(params[:id])
    @myquestions = @user.myquestions
  end

  def likes
    @user = User.find_by(id: params[:id])
    @pins = Pin.where(user_id: @user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/myquestions_helper.rb
module MyquestionsHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/quiz_helper.rb
module QuizHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def current_user?(user)
    user == current_user
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Habitus</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" name="viewport" />
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class='header'>
      <div class='image'>
        <a href = '/' ><%= image_tag "/menneske.png", size: '170x50'%></a>
       </div>
       <div class='header-nav'>
          <% if user_signed_in? %>
          <div class="grid-6">
            <%= link_to "マイページ", user_path(current_user) , class: 'nav'%>
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class:'nav' %>
          </div>
        <% else %>
          <div class="grid-6">
            <%= link_to "ログイン", new_user_session_path, class: 'nav' %>
            <%= link_to "新規登録",  new_user_registration_path, class: 'nav' %>
          </div>
        <% end %>
       </div>
    </div>
    <%= yield %>
  </body>
</html>

app/views/myquestions/new.html.erb
<div class ='form-wrapper'>
  <div class="content__title">
    質問を作成する
  </div>
  <div class='content__form'>
    <%= form_with model: @myquestion, class: :form, local: true do |form| %>
      <%= form.text_area :content, placeholder: :質問内容, class: :form__text %>
      <%= form.submit '作成', class: :form__btn %>
    <% end %>
  </div>
</div>

app/views/pins/create.html.erb
<h1>Pins#create</h1>
<p>Find me in app/views/pins/create.html.erb</p>

app/views/pins/destroy.html.erb
<h1>Pins#destroy</h1>
<p>Find me in app/views/pins/destroy.html.erb</p>

app/views/questions/about.html.erb
<div class='about-wrapper'>
  <div class='about-title'>
    遊び方
  </div>
  <div class='top-container'>
    <div class='left-container'>
      <div class='explains'>
        <div class='explain'>
          <div class='num'>①</div>
          <div class='text'>
            始めるボタンを押して、ランダムに出てくる質問をみる<br>
          </div>
        </div>
        <div class='explain'>
          <div class='num'>②</div>
          <div class='text'>
            質問に対して自身の感覚を数値化する（数値化に正解はないので自分の感覚で１〜５を選んでみる）<br>
          </div>
        </div>
         <div class='explain'>
          <div class='num'>③</div>
          <div class='text'>
            対話をするパートナーもしくは複数人と「せーの、」で数字を共有する。
            数字の共有は何かものを使っても良い。（数字をマッチ棒の本数で表してみるなど）
          </div>
        </div>
        <div class='explain'>
          <div class='num'>④</div>
          <div class='text'>
            その数字を元に「なぜそう思ったか」を話し合ってみる。その際に気になることがあればどんどん聞いてみる<br>
          </div>
        </div>
        <div class='explain'>
          <div class='num'>⑤</div>
          <div class='text'>
           一通り話し終えたら「次に進む」or「終了する」を選ぶ<br>
          </div>
        </div>
      </div>
    </div>
    <div class='right-container'>
       <%= image_tag asset_path('6c959aa37c7e927cb8297551d84943b7.jpg'), :width=> '250'%>
    </div>
  </div>
</div>

app/views/questions/index.html.erb
<script src='question.js'></script>


<div class='main-container'>
  <h1>質問一覧表</h1>
  <div class='questions'>
    <div class='question'>
      <% @questions.each do |question| %>
        <div class= 'content'>
          <span>Q.</span> <div class='text'><%= question.content %></div>
        </div>
        <% if user_signed_in? %>
          <%= form_for(question.pins.build) do |f| %>
            <%= hidden_field_tag :question_id, question.id %>
            <%= f.submit 'ピン留めする', class: 'btn btn-primary' %>
          <% end %>
        <% end %>
      <% end %>
    </div>
    <%= paginate(@questions) %>
  </div>
</div>

app/views/questions/quiz.html.erb
<div class ='show'>
  <div class='quiz'>
    <div class='Q-mark'>
      Q
    </div>
    <div class ='quiz-box'>
      <div class='quiz-content'>
        <div class='text'><%= @quiz.content %></div>
      </div>
      <div class='score'>
        <div class='score-sentence'>
          あなたの感覚値を相手と共有し、話し合ってみましょう。<br>
          <div class='point'>
            ※とてもそう思うなら「５」、全く思わないなら「１」
          </div>
        </div>
        <div class='score-number'>
          12345
        </div>
      </div>
    </div>
    <div class='next-btn-section'>
      <div class='next-btn'>
        <%= link_to '次の対話へ', quiz_questions_path, class: "next" %>
      </div>
      <div class='finish-btn'>
        <%= link_to '終了する', top_questions_path , class: "finish"%>
      </div>  
    </div>
  </div>
</div>

<script type='text/javascript'>
$('next').click(function(){

})
</script>

app/views/questions/top.html.erb
<div class='main-wrapper'>
  <div class='main-box'>
    <div class='game-title'>
      <h1>対話タイム</h1>
    </div>
    <div class='game-image'>
      <%= image_tag asset_path('1fc051097fc4d4fc2b5b08c1f339facd.jpg'),:width=>'250'%>
    </div>
    <div class='quiz-wrapper'>
      <div class='quiz-btn'>
        <%= link_to '始める',quiz_questions_path ,class: "quiz-start"%>
      </div>
      <div class='option'>
        <div class='about-btn'>
          <%= link_to '遊び方',about_questions_path ,class: "how-to-play"%>
        </div>
          <div class='index-btn'>
          <%= link_to '質問一覧',questions_path ,class: "index"%>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class='whole-wrapper'>
  <div class= 'account-name'>
    <%= current_user.nickname %>のアカウント
  </div>
  <div class='pic'>
    <%= image_tag '/tumblr_nlnelvRVPX1sczrxso1_1280.jpg', :width=> '250'%>
  </div>
  <div class='btn-wrapper'>
    <div class='btns'>
      <div class='btn'>
        <div class='question-btn'>
          <%= link_to '質問を作る', new_myquestion_path %>
        </div>
      </div>
      <div class='btn'>
        <div class='index-btn'>
          <%= link_to '一覧を見る',questions_path %>
        </div>
      </div>
    </div>
  </div>
  
  <div class='post-wrapper'>
    <div class='questions-box'>
      <div class='questions'>
        <div class='users-questions'>
          <div class='users-questions__title'>
            自分が作成した質問
          </div>
          <div class='users-questions__list'>
            <% @myquestions.each do | myquestion | %>
              <div class='myquestion'>
                <div class= 'question-content'>
                  <span>Q.</span> <div class='text'><%= myquestion.content %></div>
                </div>
                <div class='myquestion-btn'>
                  <%= link_to '削除', myquestion_path(myquestion.id), method: :delete ,class:'delete'%>
                </div>
              </div>
            <%end%>
          </div>
        </div>
      </div>  
      <%= @quiz %>
      <div class='questions'>
        <div class='pins-questions'>
          <p class ='user-like'>
            自分がピン留めした質問
          </p>
          <div class='user-like__list'>
            <% current_user.questions.each do |question| %>
              <div class='pin'>
                <div class='pin-content'>
                  <span>Q.</span><div class='text'><%= question.content %></div>
                </div>
                <div class='remove-btn'>
                  <%= form_for(question.pins.find_by(user_id: current_user.id), method: :delete ) do |f| %> 
                    <%= hidden_field_tag :question_id, question.id %>
                    <%= f.submit "ピンを外す", class: "btn btn-outline-success" %>
                  <% end %>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>  
      
    </div>
  </div>
</div>